

import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author swapnil
 */ 
public class Student_Form_1 extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Student_Form_1() {
        initComponents();
            this.setLocationRelativeTo(null);
            this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField3_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4_mobno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5_uid = new javax.swing.JTextField();
        jPasswordField1_pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2_add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2_institution = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTextField6_iname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1_medium = new javax.swing.JComboBox();
        jTextField7_class = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_sub = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        nlab = new javax.swing.JLabel();
        elab = new javax.swing.JLabel();
        mlab = new javax.swing.JLabel();
        ilab = new javax.swing.JLabel();
        plab = new javax.swing.JLabel();
        alab = new javax.swing.JLabel();
        inlab = new javax.swing.JLabel();
        slab = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jRadioButton3.setText("jRadioButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 52, 56));

        jPanel2.setBackground(new java.awt.Color(163, 163, 163));

        jTextField3_name.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField3_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_nameActionPerformed(evt);
            }
        });
        jTextField3_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3_nameKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Name");

        jTextField1_email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField1_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_emailActionPerformed(evt);
            }
        });
        jTextField1_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_emailKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mobile no");

        jTextField4_mobno.setForeground(new java.awt.Color(0, 102, 204));
        jTextField4_mobno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField4_mobno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4_mobnoActionPerformed(evt);
            }
        });
        jTextField4_mobno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4_mobnoKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("User Id");

        jTextField5_uid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField5_uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5_uidActionPerformed(evt);
            }
        });
        jTextField5_uid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5_uidKeyReleased(evt);
            }
        });

        jPasswordField1_pass.setForeground(new java.awt.Color(0, 102, 255));
        jPasswordField1_pass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jPasswordField1_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1_passActionPerformed(evt);
            }
        });
        jPasswordField1_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1_passKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Password");

        jTextField2_add.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField2_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_addActionPerformed(evt);
            }
        });
        jTextField2_add.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2_addKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Address");

        jComboBox2_institution.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primary School", "School", "colloge", "University", "Dakhil" }));
        jComboBox2_institution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2_institutionActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 73, 78));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Intitution");

        jTextField6_iname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField6_iname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6_inameActionPerformed(evt);
            }
        });
        jTextField6_iname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6_inameKeyReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 73, 78));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Institution Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Gender");

        jRadioButton1.setBackground(new java.awt.Color(163, 163, 163));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setText("Male");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setBackground(new java.awt.Color(163, 163, 163));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("Female");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Medium");

        jComboBox1_medium.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangla", "English", "Dakhil" }));
        jComboBox1_medium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1_mediumActionPerformed(evt);
            }
        });

        jTextField7_class.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextField7_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7_classActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Class");

        jButton2.setBackground(new java.awt.Color(163, 163, 163));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(163, 163, 163));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Tution_Media\\image\\iconfinder_Button_Back_72907.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1_sub.setColumns(20);
        jTextArea1_sub.setRows(5);
        jTextArea1_sub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.blue));
        jTextArea1_sub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1_subKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1_sub);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Subject");

        jButton1.setBackground(new java.awt.Color(163, 163, 163));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("Agree & Join");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(163, 163, 163));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Tution_Media\\image\\pi.jpg")); // NOI18N

        nlab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nlab.setForeground(new java.awt.Color(255, 0, 51));

        elab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        elab.setForeground(new java.awt.Color(255, 0, 0));

        mlab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mlab.setForeground(new java.awt.Color(255, 51, 51));

        ilab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ilab.setForeground(new java.awt.Color(255, 51, 51));

        plab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        plab.setForeground(new java.awt.Color(255, 0, 0));

        alab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        alab.setForeground(new java.awt.Color(255, 0, 0));

        inlab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        inlab.setForeground(new java.awt.Color(255, 51, 51));

        slab.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        slab.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField2_add, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(alab, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jPasswordField1_pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addComponent(jTextField3_name)
                                            .addComponent(jTextField4_mobno, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1_email, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField5_uid))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(elab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ilab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(plab, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13)))
                                .addContainerGap())
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jComboBox2_institution, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton2)))
                                        .addGap(16, 16, 16))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBox1_medium, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7_class, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6_iname, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inlab, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 28, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(slab, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nlab, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_email, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(elab, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4_mobno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mlab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5_uid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ilab, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField1_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plab, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2_add, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2_institution, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6_iname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inlab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1_medium, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7_class, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slab, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailActionPerformed

    private void jTextField3_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_nameActionPerformed

    private void jTextField4_mobnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4_mobnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_mobnoActionPerformed

    private void jTextField5_uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_uidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name=jTextField3_name.getText().toString();
        String email=jTextField1_email.getText().toString();
        String mobno=jTextField4_mobno.getText().toString();
        String id=jTextField5_uid.getText().toString();
        String pass=jPasswordField1_pass.getText().toString();
        String add =jTextField2_add.getText().toString();
        String iname =jTextField6_iname.getText().toString();
        String subj =jTextArea1_sub.getText().toString();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your name");
        }
        if(email.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your email");
        }
        if(mobno.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your Mobile no");
        }
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your id");
        }
        if(pass.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your password");
        }
        if(add.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your address");
        }
        if(iname.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your Institution name");
        }
        
        if(subj.equals("")){
            JOptionPane.showMessageDialog(null,"Enter your Institution subject");
        }
        
        
        
        else
        {
         ArrayList sInfo = new ArrayList();
        sInfo.add( jTextField3_name.getText());
        sInfo.add(jTextField1_email.getText());
        sInfo.add(jTextField4_mobno.getText());
        sInfo.add(jTextField5_uid.getText());
        sInfo.add(jPasswordField1_pass.getText());
        sInfo.add(jTextField2_add.getText());
        sInfo.add(jComboBox2_institution.getSelectedItem());
        sInfo.add(jTextField6_iname.getText());
        String radioChoice = "";
        if(jRadioButton1.isSelected()){
        radioChoice = jRadioButton1.getText();
        }
        if(jRadioButton2.isSelected()){
        radioChoice = jRadioButton2.getText();
        }
        sInfo.add(radioChoice);
        sInfo.add(jComboBox1_medium.getSelectedItem());
        sInfo.add( jTextField7_class.getText());
        sInfo.add( jTextArea1_sub.getText());
        //now inserting into database
        DBConnector dbc = new DBConnector();
        dbc.insertIntoDB(sInfo);
        //populateJTableOnFormLoad();
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jTextField2_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_addActionPerformed

    private void jTextField7_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7_classActionPerformed

    private void jPasswordField1_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_passActionPerformed

    private void jComboBox1_mediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1_mediumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1_mediumActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Type_Form typ=new Type_Form();
this.setVisible(false);
typ.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6_inameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6_inameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6_inameActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jComboBox2_institutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2_institutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2_institutionActionPerformed

    private void jTextField3_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3_nameKeyReleased
 String PATTERN="^[ a-zA-Z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField3_name.getText());
        if(!match.matches()){
    nlab.setText("invalid!!");
        }
        else{
            nlab.setText(null);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_nameKeyReleased

    private void jTextField1_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_emailKeyReleased
 String PATTERN="^[a-zA-Z0-9]{0,30}@[a-zA-z]{0,10}.[a-zA-z]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField1_email.getText());
        if(!match.matches()){
    elab.setText("invalid!!");
        }
        else{
            elab.setText(null);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_emailKeyReleased

    private void jTextField4_mobnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4_mobnoKeyReleased
 String PATTERN="^[0-9]{0,11}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField4_mobno.getText());
        if(!match.matches()){
    mlab.setText("invalid!!");
        }
        else{
            mlab.setText(null);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_mobnoKeyReleased

    private void jPasswordField1_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1_passKeyReleased
 String PATTERN="^[0-9]{5,15}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jPasswordField1_pass.getText());
        if(!match.matches()){
    plab.setText("invalid!!");
        }
        else{
            plab.setText(null);
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1_passKeyReleased

    private void jTextField5_uidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5_uidKeyReleased
        String PATTERN="^[0-9]{5,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField5_uid.getText());
        if(!match.matches()){
    ilab.setText("invalid!!");
        }
        else{
            ilab.setText(null);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5_uidKeyReleased

    private void jTextField2_addKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2_addKeyReleased
      String PATTERN="^[a-zA-Z0-9-,]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField2_add.getText());
        if(!match.matches()){
    alab.setText("invalid!!");
        }
        else{
            alab.setText(null);
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_addKeyReleased

    private void jTextField6_inameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6_inameKeyReleased
String PATTERN="^[a-zA-Z-. ]{0,40}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextField6_iname.getText());
        if(!match.matches()){
    inlab.setText("invalid!!");
        }
        else{
            inlab.setText(null);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6_inameKeyReleased

    private void jTextArea1_subKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1_subKeyReleased
       String PATTERN="^[a-zA-Z-,]{0,20}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt .matcher(jTextArea1_sub.getText());
        if(!match.matches()){
    slab.setText("invalid!!");
        }
        else{
            slab.setText(null);
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1_subKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Form_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Form_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Form_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Form_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Form_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel elab;
    private javax.swing.JLabel ilab;
    private javax.swing.JLabel inlab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1_medium;
    private javax.swing.JComboBox jComboBox2_institution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1_pass;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1_sub;
    private javax.swing.JTextField jTextField1_email;
    private javax.swing.JTextField jTextField2_add;
    private javax.swing.JTextField jTextField3_name;
    private javax.swing.JTextField jTextField4_mobno;
    private javax.swing.JTextField jTextField5_uid;
    private javax.swing.JTextField jTextField6_iname;
    private javax.swing.JTextField jTextField7_class;
    private javax.swing.JLabel mlab;
    private javax.swing.JLabel nlab;
    private javax.swing.JLabel plab;
    private javax.swing.JLabel slab;
    // End of variables declaration//GEN-END:variables
 
    
    
    
}
